// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Acid_fbb597bf757ae124a9420852a332f640Index = 0;
		public const int Explosion_0c25a96a0fb615348b57d8131f1fc940Index = 1;
		public const int Player_3b896e424d82c884d9d345e909e13ea9Index = 2;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Acid_fbb597bf757ae124a9420852a332f640", 0 },

			{ "Explosion_0c25a96a0fb615348b57d8131f1fc940", 1 },

			{ "Player_3b896e424d82c884d9d345e909e13ea9", 2 },

		};
	}
}
