// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct AreaMover_id5_MapJoin__char_46_RequestSpawnpoint_7b12f40c_7295_45d5_acf7_e6a4ced8efe2 : IEntityCommand
	{
		public SerializeEntityID player;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalAreaMover_id5_MapJoin__char_46_RequestSpawnpoint_7b12f40c_7295_45d5_acf7_e6a4ced8efe2;

		public AreaMover_id5_MapJoin__char_46_RequestSpawnpoint_7b12f40c_7295_45d5_acf7_e6a4ced8efe2
		(
			SerializeEntityID dataplayer
		)
		{
			player = dataplayer;
		}

		public static void Serialize(AreaMover_id5_MapJoin__char_46_RequestSpawnpoint_7b12f40c_7295_45d5_acf7_e6a4ced8efe2 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteEntity(commandData.player);
		}

		public static AreaMover_id5_MapJoin__char_46_RequestSpawnpoint_7b12f40c_7295_45d5_acf7_e6a4ced8efe2 Deserialize(IInProtocolBitStream bitStream)
		{
			var dataplayer = bitStream.ReadEntity();

			return new AreaMover_id5_MapJoin__char_46_RequestSpawnpoint_7b12f40c_7295_45d5_acf7_e6a4ced8efe2
			(
				dataplayer
			){};
		}
	}
}
