// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct BulletTrail_id6_ProjectileTrail_4771486144989202667 : ICoherenceComponentData
	{
		public Vector3 EndPosSync;

		public override string ToString()
		{
			return $"BulletTrail_id6_ProjectileTrail_4771486144989202667(EndPosSync: {EndPosSync})";
		}

		public uint GetComponentType() => Definition.InternalBulletTrail_id6_ProjectileTrail_4771486144989202667;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (BulletTrail_id6_ProjectileTrail_4771486144989202667)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				EndPosSync = other.EndPosSync;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(BulletTrail_id6_ProjectileTrail_4771486144989202667 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteVector3((data.EndPosSync.ToCoreVector3()), FloatMeta.NoCompression());
			}
			mask >>= 1;
		}

		public static (BulletTrail_id6_ProjectileTrail_4771486144989202667, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new BulletTrail_id6_ProjectileTrail_4771486144989202667();
	
			if (bitStream.ReadMask())
			{
				val.EndPosSync = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask, null);
		}
		public static (BulletTrail_id6_ProjectileTrail_4771486144989202667, uint, uint?) DeserializeArchetypeBulletTrail_8a9e96fc2de52284c98b4f0d8a3ba0a1_BulletTrail_id6_ProjectileTrail_4771486144989202667_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new BulletTrail_id6_ProjectileTrail_4771486144989202667();
			if (bitStream.ReadMask())
			{
				val.EndPosSync = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as BulletTrail_id6_ProjectileTrail_4771486144989202667?;
	
		}
	}
}