// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_ec84610ffed7f904db8ab89dc4452e37_0d2164fc_1699_4534_9c80_e4ea8fad2510 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_ec84610ffed7f904db8ab89dc4452e37_95571017_8fea_404c_9336_099ccbb6ef2d : UIntBinding
	{
		private PlayerList CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlayerList)UnityComponent;
		}
		public override string CoherenceComponentName => "SystemsSynced_id4_PlayerList_5830596318896160362";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override uint Value
		{
			get => (uint)(System.UInt32)(CastedUnityComponent.nextId);
			set => CastedUnityComponent.nextId = (System.UInt32)(value);
		}

		protected override uint ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((SystemsSynced_id4_PlayerList_5830596318896160362)coherenceComponent).nextId;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (SystemsSynced_id4_PlayerList_5830596318896160362)coherenceComponent;
			update.nextId = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new SystemsSynced_id4_PlayerList_5830596318896160362();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'SystemsSynced' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncSystemsSynced_id4 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private PlayerList SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d_CommandTarget;		
		private PlayerList SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197_CommandTarget;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncSystemsSynced_id4>();
			if (coherenceSync.TryGetBindingByGuid("24e85083-9792-4229-b5a9-280445e1912d", "AssignPlayerIdAndName", out Binding SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d))
			{
				SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d_CommandTarget = (PlayerList)SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("PlayerList.AssignPlayerIdAndName", "(Coherence.Toolkit.CoherenceSyncSystem.String)",
				SendCommand_SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d, ReceiveLocalCommand_SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d, MessageTarget.AuthorityOnly, SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (AssignPlayerIdAndName)");
			}
			if (coherenceSync.TryGetBindingByGuid("627a7098-4a40-4ea8-8f49-5d50b2c5e197", "BindPlayerIdAndName", out Binding SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197))
			{
				SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197_CommandTarget = (PlayerList)SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("PlayerList.BindPlayerIdAndName", "(Coherence.Toolkit.CoherenceSyncSystem.StringSystem.UInt32)",
				SendCommand_SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197, ReceiveLocalCommand_SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197, MessageTarget.All, SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (BindPlayerIdAndName)");
			}
			if (coherenceSync.TryGetBindingByGuid("0d2164fc-1699-4534-9c80-e4ea8fad2510", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_ec84610ffed7f904db8ab89dc4452e37_0d2164fc_1699_4534_9c80_e4ea8fad2510();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("95571017-8fea-404c-9336-099ccbb6ef2d", "nextId", out Binding InternalSystemsSynced_id4_PlayerList_5830596318896160362_SystemsSynced_id4_PlayerList_5830596318896160362_nextId))
			{
				var clone = new Binding_ec84610ffed7f904db8ab89dc4452e37_95571017_8fea_404c_9336_099ccbb6ef2d();
				InternalSystemsSynced_id4_PlayerList_5830596318896160362_SystemsSynced_id4_PlayerList_5830596318896160362_nextId.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSystemsSynced_id4_PlayerList_5830596318896160362_SystemsSynced_id4_PlayerList_5830596318896160362_nextId)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlayerList).nextId");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}
		void SendCommand_SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d(MessageTarget target, object[] args)
		{
			var command = new SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d();
			int i = 0;
			command.targetPlayerSync = (SerializeEntityID)monoBridge.UnityObjectToEntityId(args[i++] as CoherenceSync);
			command.playerName = (string)((System.String)args[i++]);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d(MessageTarget target, object[] args)
		{
			var command = new SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d();
			int i = 0;
			command.targetPlayerSync = (SerializeEntityID)monoBridge.UnityObjectToEntityId(args[i++] as CoherenceSync);
			command.playerName = (string)((System.String)args[i++]);
			ReceiveCommand_SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d(command);
		}

		void ReceiveCommand_SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d(SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d command)
		{
			var target = SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d_CommandTarget;
			target.AssignPlayerIdAndName(monoBridge.EntityIdToCoherenceSync(command.targetPlayerSync),(System.String)(command.playerName));
		}
		void SendCommand_SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197(MessageTarget target, object[] args)
		{
			var command = new SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197();
			int i = 0;
			command.targetPlayerSync = (SerializeEntityID)monoBridge.UnityObjectToEntityId(args[i++] as CoherenceSync);
			command.playerName = (string)((System.String)args[i++]);
			command.id = (uint)((System.UInt32)args[i++]);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197(MessageTarget target, object[] args)
		{
			var command = new SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197();
			int i = 0;
			command.targetPlayerSync = (SerializeEntityID)monoBridge.UnityObjectToEntityId(args[i++] as CoherenceSync);
			command.playerName = (string)((System.String)args[i++]);
			command.id = (uint)((System.UInt32)args[i++]);
			ReceiveCommand_SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197(command);
		}

		void ReceiveCommand_SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197(SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197 command)
		{
			var target = SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197_CommandTarget;
			target.BindPlayerIdAndName(monoBridge.EntityIdToCoherenceSync(command.targetPlayerSync),(System.String)(command.playerName),(System.UInt32)(command.id));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d castedCommand:
					ReceiveCommand_SystemsSynced_id4_PlayerList__char_46_AssignPlayerIdAndName_24e85083_9792_4229_b5a9_280445e1912d(castedCommand);
					break;
				case SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197 castedCommand:
					ReceiveCommand_SystemsSynced_id4_PlayerList__char_46_BindPlayerIdAndName_627a7098_4a40_4ea8_8f49_5d50b2c5e197(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncSystemsSynced_id4] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
