// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_3b896e424d82c884d9d345e909e13ea9_406d0057_fba8_43e8_bfb8_6bf37c28e701 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_3b896e424d82c884d9d345e909e13ea9_f6d8171a_bf23_4f6d_beb0_d5eaf1d441f4 : IntBinding
	{
		private PlayerHP CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlayerHP)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_PlayerHP_520862196960591170";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.SyncHP);
			set => CastedUnityComponent.SyncHP = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_id0_PlayerHP_520862196960591170)coherenceComponent).SyncHP;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_PlayerHP_520862196960591170)coherenceComponent;
			update.SyncHP = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_PlayerHP_520862196960591170();
		}
	}

	public class Binding_3b896e424d82c884d9d345e909e13ea9_187ffbe0_18e5_429d_ba71_70eb0234f13a : IntBinding
	{
		private PlayerHP CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlayerHP)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_PlayerHP_520862196960591170";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.SyncMaxHP);
			set => CastedUnityComponent.SyncMaxHP = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_id0_PlayerHP_520862196960591170)coherenceComponent).SyncMaxHP;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_PlayerHP_520862196960591170)coherenceComponent;
			update.SyncMaxHP = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_PlayerHP_520862196960591170();
		}
	}

	public class Binding_3b896e424d82c884d9d345e909e13ea9_6dfae5aa_d9d8_4842_94ac_77e7e9313440 : StringBinding
	{
		private PlayerInfo CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlayerInfo)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_PlayerInfo_3474864809680843249";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override string Value
		{
			get => (string)(System.String)(CastedUnityComponent.PlayerName);
			set => CastedUnityComponent.PlayerName = (System.String)(value);
		}

		protected override string ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_id0_PlayerInfo_3474864809680843249)coherenceComponent).PlayerName;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_PlayerInfo_3474864809680843249)coherenceComponent;
			update.PlayerName = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_PlayerInfo_3474864809680843249();
		}
	}

	public class Binding_3b896e424d82c884d9d345e909e13ea9_e91e5677_3f0b_424e_b85f_66e6b9a762b4 : IntBinding
	{
		private PlayerInfo CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlayerInfo)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_PlayerInfo_3474864809680843249";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.DeathCountSync);
			set => CastedUnityComponent.DeathCountSync = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_id0_PlayerInfo_3474864809680843249)coherenceComponent).DeathCountSync;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_PlayerInfo_3474864809680843249)coherenceComponent;
			update.DeathCountSync = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_PlayerInfo_3474864809680843249();
		}
	}

	public class Binding_3b896e424d82c884d9d345e909e13ea9_ee8f0d5f_c419_4835_ae0a_c8db5eb87aae : IntBinding
	{
		private PlayerInfo CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlayerInfo)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_PlayerInfo_3474864809680843249";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.KillCountSync);
			set => CastedUnityComponent.KillCountSync = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_id0_PlayerInfo_3474864809680843249)coherenceComponent).KillCountSync;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_PlayerInfo_3474864809680843249)coherenceComponent;
			update.KillCountSync = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_PlayerInfo_3474864809680843249();
		}
	}

	public class Binding_3b896e424d82c884d9d345e909e13ea9_d0f8d3b3_0003_4149_b980_7338387faebe : UIntBinding
	{
		private PlayerInfo CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (PlayerInfo)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_PlayerInfo_3474864809680843249";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override uint Value
		{
			get => (uint)(System.UInt32)(CastedUnityComponent.PlayerId);
			set => CastedUnityComponent.PlayerId = (System.UInt32)(value);
		}

		protected override uint ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_id0_PlayerInfo_3474864809680843249)coherenceComponent).PlayerId;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_PlayerInfo_3474864809680843249)coherenceComponent;
			update.PlayerId = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_PlayerInfo_3474864809680843249();
		}
	}

	public class Binding_3b896e424d82c884d9d345e909e13ea9_ee745906_d1ab_461e_9049_1780b0f3f185 : DeepRotationBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Transform_2639605840214257464";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(CastedUnityComponent.localRotation);
			set => CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player_id0_UnityEngine__char_46_Transform_2639605840214257464)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_2639605840214257464)coherenceComponent;
			update.rotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Transform_2639605840214257464();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Player' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncPlayer_id0 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private PlayerInfo Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495_CommandTarget;		
		private PlayerRespawner Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c_CommandTarget;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncPlayer_id0>();
			if (coherenceSync.TryGetBindingByGuid("5279bc1c-9c3c-4812-b835-3461824ce495", "AddKillInternal", out Binding Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495))
			{
				Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495_CommandTarget = (PlayerInfo)Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("PlayerInfo.AddKillInternal", "()",
				SendCommand_Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495, ReceiveLocalCommand_Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495, MessageTarget.AuthorityOnly, Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (AddKillInternal)");
			}
			if (coherenceSync.TryGetBindingByGuid("855a22e0-4761-412a-b3b6-4f4db3d1c40c", "RespawnInternal", out Binding Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c))
			{
				Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c_CommandTarget = (PlayerRespawner)Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("PlayerRespawner.RespawnInternal", "(System.Int32)",
				SendCommand_Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c, ReceiveLocalCommand_Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c, MessageTarget.AuthorityOnly, Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (RespawnInternal)");
			}
			if (coherenceSync.TryGetBindingByGuid("406d0057-fba8-43e8-bfb8-6bf37c28e701", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_3b896e424d82c884d9d345e909e13ea9_406d0057_fba8_43e8_bfb8_6bf37c28e701();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("f6d8171a-bf23-4f6d-beb0-d5eaf1d441f4", "SyncHP", out Binding InternalPlayer_id0_PlayerHP_520862196960591170_Player_id0_PlayerHP_520862196960591170_SyncHP))
			{
				var clone = new Binding_3b896e424d82c884d9d345e909e13ea9_f6d8171a_bf23_4f6d_beb0_d5eaf1d441f4();
				InternalPlayer_id0_PlayerHP_520862196960591170_Player_id0_PlayerHP_520862196960591170_SyncHP.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_PlayerHP_520862196960591170_Player_id0_PlayerHP_520862196960591170_SyncHP)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlayerHP).SyncHP");
			}
			if (coherenceSync.TryGetBindingByGuid("187ffbe0-18e5-429d-ba71-70eb0234f13a", "SyncMaxHP", out Binding InternalPlayer_id0_PlayerHP_520862196960591170_Player_id0_PlayerHP_520862196960591170_SyncMaxHP))
			{
				var clone = new Binding_3b896e424d82c884d9d345e909e13ea9_187ffbe0_18e5_429d_ba71_70eb0234f13a();
				InternalPlayer_id0_PlayerHP_520862196960591170_Player_id0_PlayerHP_520862196960591170_SyncMaxHP.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_PlayerHP_520862196960591170_Player_id0_PlayerHP_520862196960591170_SyncMaxHP)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlayerHP).SyncMaxHP");
			}
			if (coherenceSync.TryGetBindingByGuid("6dfae5aa-d9d8-4842-94ac-77e7e9313440", "PlayerName", out Binding InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_PlayerName))
			{
				var clone = new Binding_3b896e424d82c884d9d345e909e13ea9_6dfae5aa_d9d8_4842_94ac_77e7e9313440();
				InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_PlayerName.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_PlayerName)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlayerInfo).PlayerName");
			}
			if (coherenceSync.TryGetBindingByGuid("e91e5677-3f0b-424e-b85f-66e6b9a762b4", "DeathCountSync", out Binding InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_DeathCountSync))
			{
				var clone = new Binding_3b896e424d82c884d9d345e909e13ea9_e91e5677_3f0b_424e_b85f_66e6b9a762b4();
				InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_DeathCountSync.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_DeathCountSync)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlayerInfo).DeathCountSync");
			}
			if (coherenceSync.TryGetBindingByGuid("ee8f0d5f-c419-4835-ae0a-c8db5eb87aae", "KillCountSync", out Binding InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_KillCountSync))
			{
				var clone = new Binding_3b896e424d82c884d9d345e909e13ea9_ee8f0d5f_c419_4835_ae0a_c8db5eb87aae();
				InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_KillCountSync.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_KillCountSync)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlayerInfo).KillCountSync");
			}
			if (coherenceSync.TryGetBindingByGuid("d0f8d3b3-0003-4149-b980-7338387faebe", "PlayerId", out Binding InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_PlayerId))
			{
				var clone = new Binding_3b896e424d82c884d9d345e909e13ea9_d0f8d3b3_0003_4149_b980_7338387faebe();
				InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_PlayerId.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_PlayerInfo_3474864809680843249_Player_id0_PlayerInfo_3474864809680843249_PlayerId)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (PlayerInfo).PlayerId");
			}
			if (coherenceSync.TryGetBindingByGuid("ee745906-d1ab-461e-9049-1780b0f3f185", "rotation", out Binding InternalPlayer_id0_UnityEngine__char_46_Transform_2639605840214257464_Player_id0_UnityEngine__char_46_Transform_2639605840214257464_rotation))
			{
				var clone = new Binding_3b896e424d82c884d9d345e909e13ea9_ee745906_d1ab_461e_9049_1780b0f3f185();
				InternalPlayer_id0_UnityEngine__char_46_Transform_2639605840214257464_Player_id0_UnityEngine__char_46_Transform_2639605840214257464_rotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Transform_2639605840214257464_Player_id0_UnityEngine__char_46_Transform_2639605840214257464_rotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}
		void SendCommand_Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495();
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495();
			ReceiveCommand_Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495(command);
		}

		void ReceiveCommand_Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495(Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495 command)
		{
			var target = Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495_CommandTarget;
			target.AddKillInternal();
		}
		void SendCommand_Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c();
			int i = 0;
			command.spawnpoint = (int)((System.Int32)args[i++]);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c();
			int i = 0;
			command.spawnpoint = (int)((System.Int32)args[i++]);
			ReceiveCommand_Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c(command);
		}

		void ReceiveCommand_Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c(Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c command)
		{
			var target = Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c_CommandTarget;
			target.RespawnInternal((System.Int32)(command.spawnpoint));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495 castedCommand:
					ReceiveCommand_Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495(castedCommand);
					break;
				case Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c castedCommand:
					ReceiveCommand_Player_id0_PlayerRespawner__char_46_RespawnInternal_855a22e0_4761_412a_b3b6_4f4db3d1c40c(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncPlayer_id0] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
