// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495;

		public static void Serialize(Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_id0_PlayerInfo__char_46_AddKillInternal_5279bc1c_9c3c_4812_b835_3461824ce495
			(
			){};
		}
	}
}
