// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Player_id0_PlayerInfo_3474864809680843249 : ICoherenceComponentData
	{
		public string PlayerName;
		public int DeathCountSync;
		public int KillCountSync;
		public uint PlayerId;

		public override string ToString()
		{
			return $"Player_id0_PlayerInfo_3474864809680843249(PlayerName: {PlayerName}, DeathCountSync: {DeathCountSync}, KillCountSync: {KillCountSync}, PlayerId: {PlayerId})";
		}

		public uint GetComponentType() => Definition.InternalPlayer_id0_PlayerInfo_3474864809680843249;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _DeathCountSync_Min = -2147483648;
		private static readonly int _DeathCountSync_Max = 2147483647;
		private static readonly int _KillCountSync_Min = -2147483648;
		private static readonly int _KillCountSync_Max = 2147483647;
		private static readonly uint _PlayerId_Min = 0;
		private static readonly uint _PlayerId_Max = 4294967295;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Player_id0_PlayerInfo_3474864809680843249)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				PlayerName = other.PlayerName;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				DeathCountSync = other.DeathCountSync;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				KillCountSync = other.KillCountSync;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				PlayerId = other.PlayerId;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(Player_id0_PlayerInfo_3474864809680843249 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteShortString(data.PlayerName);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.DeathCountSync, _DeathCountSync_Min, _DeathCountSync_Max, "Player_id0_PlayerInfo_3474864809680843249.DeathCountSync");
				data.DeathCountSync = Coherence.Utils.Bounds.Clamp(data.DeathCountSync, _DeathCountSync_Min, _DeathCountSync_Max);
				bitStream.WriteIntegerRange(data.DeathCountSync, 32, -2147483648);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.KillCountSync, _KillCountSync_Min, _KillCountSync_Max, "Player_id0_PlayerInfo_3474864809680843249.KillCountSync");
				data.KillCountSync = Coherence.Utils.Bounds.Clamp(data.KillCountSync, _KillCountSync_Min, _KillCountSync_Max);
				bitStream.WriteIntegerRange(data.KillCountSync, 32, -2147483648);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.PlayerId, _PlayerId_Min, _PlayerId_Max, "Player_id0_PlayerInfo_3474864809680843249.PlayerId");
				data.PlayerId = Coherence.Utils.Bounds.Clamp(data.PlayerId, _PlayerId_Min, _PlayerId_Max);
				bitStream.WriteUIntegerRange(data.PlayerId, 32, 0);
			}
			mask >>= 1;
		}

		public static (Player_id0_PlayerInfo_3474864809680843249, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Player_id0_PlayerInfo_3474864809680843249();
	
			if (bitStream.ReadMask())
			{
				val.PlayerName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.DeathCountSync = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.KillCountSync = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.PlayerId = bitStream.ReadUIntegerRange(32, 0);
				mask |= 0b00000000000000000000000000001000;
			}
			return (val, mask, null);
		}
		public static (Player_id0_PlayerInfo_3474864809680843249, uint, uint?) DeserializeArchetypePlayer_3b896e424d82c884d9d345e909e13ea9_Player_id0_PlayerInfo_3474864809680843249_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Player_id0_PlayerInfo_3474864809680843249();
			if (bitStream.ReadMask())
			{
				val.PlayerName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.DeathCountSync = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.KillCountSync = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.PlayerId = bitStream.ReadUIntegerRange(32, 0);
				mask |= 0b00000000000000000000000000001000;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Player_id0_PlayerInfo_3474864809680843249?;
	
		}
	}
}